version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4500:4500"
    environment:
      - PORT=4500
      - CLIENT_PORT=3000
      - REACT_APP_API_URL=http://localhost:4500
    networks:
      - app-network
    volumes:
      - .:/app
      - /app/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    networks:
      - app-network
    volumes:
      - ./client:/app
      - /app/node_modules

networks:
  app-network:
    driver: bridge
